language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.npm
script:
  - yarn
  - yarn build
  - yarn examples
branches:
  only:
    - master # 只对 master 分支进行构建
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build
    github_token: $GITHUB_TOKEN
    name: $GIT_NAME
    email: $GIT_EMAIL
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $GIT_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master
      tags: true